### ISSUE TITLE
gd - unknown action: c |LESS='-R' less)

### ISSUE THREAD

**Issue by loonies** [wfxr/forgit#74] opened 2020-03-04 08:34 UTC
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

`gd` or `gd <directory>` gives the `unknown action: c |LESS='-R' less)` error.

**Comment by telefunken** [comment] 2020-03-09 12:11
I got a similar error on the same call: bind action not specified: 5 -R |LESS='-R' less)

**Comment by wfxr** [comment] 2020-03-18 03:32
I cannot reproduce the problem. Even if I changed my pager in `.gitconfig` as @telefunken 's (with or withour pipe).

Can you provide the smallest environment to reproduce this problem steadily? @loonies

**Comment by airelil** [comment] 2020-04-04 04:57
Getting the same error on Ubuntu 18.04 and bash while trying forgit online. I ran it in tmux session. Here is my short sessions and .gitconfig
```bash
XXXXXX@ubuntu18.04:~$ source <(curl -Ss https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.zsh)
XXXXXX@ubuntu18.04:~$ cd my_cpp_project/
/home/XXXXXX/src/my_cpp_project
XXXXXX@ubuntu18.04:~/src/my_cpp_project$ glo
XXXXXX@ubuntu18.04:~/src/my_cpp_project$ cd ../other_cpp_proj/
XXXXXX@ubuntu18.04:~/src/other_cpp_proj$ gd
bind action not specified: 5 |LESS='-R' less)
XXXXXX@ubuntu18.04:~/src/other_cpp_proj$ gss
bind action not specified: 5 | LESS='-R' less)
XXXXXX@ubuntu18.04:~/src/other_cpp_proj$ cd -
/home/XXXXXX/src/my_cpp_project
XXXXXX@ubuntu18.04:~/src/my_cpp_project$ gss
bind action not specified: 5 | LESS='-R' less)
XXXXXX@ubuntu18.04:~/src/my_cpp_project$ 
```
```.gitconfig
[user]
        email = nnnnnn.ffffff@cccccc.com
        name = nnnnnn.ffffff
[log]
        date = relative
[format]
        pretty = format:%h %Cblue%ad%Creset %an %Cgreen%s%Creset
[alias]
        out = log --abbrev-commit --graph @{u}..
        in = !git fetch && git log --abbrev-commit --graph ..@{u}
        lg1 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%<(65,trunc)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
        lg2 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
        lg = !"git lg1"
        serve = daemon --verbose --export-all --base-path=.git --reuseaddr --strict-paths .git/
[push]
        default = simple
[core]
        excludesFile = ~/.gitignore
        mergeoptions = --no-edit
        editor = vim
        pager = less -x1,5
[diff]
        submodule = log

```

**Comment by wfxr** [comment] 2020-04-07 07:06
@airelil Thanks for your feedback. I will look into it.

**Comment by wfxr** [comment] 2020-04-07 07:42
@airelil Sorry but I still can not reproduce the error:

```
# os info
test% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

# zshrc
test% cat ~/.zshrc
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# gitconfig
test% cat ~/.gitconfig
[user]
        email = nnnnnn.ffffff@cccccc.com
        name = nnnnnn.ffffff
[log]
        date = relative
[format]
        pretty = format:%h %Cblue%ad%Creset %an %Cgreen%s%Creset
[alias]
        out = log --abbrev-commit --graph @{u}..
        in = !git fetch && git log --abbrev-commit --graph ..@{u}
        lg1 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%<(65,trunc)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
        lg2 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
        lg = !"git lg1"
        serve = daemon --verbose --export-all --base-path=.git --reuseaddr --strict-paths .git/
[push]
        default = simple
[core]
        excludesFile = ~/.gitignore
        mergeoptions = --no-edit
        editor = vim
        pager = less -x1,5
[diff]
        submodule = log

# source plugin
test% source forgit.plugin.zsh

# run glo
test% glo

# show output blew:
```
![image](https://user-images.githubusercontent.com/6105425/78643035-3974f980-78e6-11ea-9033-1713c3b48988.png)

**Comment by wfxr** [comment] 2020-04-08 02:57
There are some problems in using the sub shell at the preview option of fzf. I rewrited it using pipe instead. You can update and try it now.  @airelil

**Comment by loonies** [comment] 2020-04-08 07:33
Works for me. Thanks

**Comment by airelil** [comment] 2020-04-08 20:24
@wfxr , thanks for the finding the time to look into the issue and for the quick fix! I can confirm that `gd` command now works for me. However, you might didn't notice in my log above, but `gss` command failed the same way for me. I guess, you could apply the same fix for `gss`, as well?

**Comment by wfxr** [comment] 2020-04-09 03:07
@airelil Fixed.

**Comment by wfxr** [comment] 2020-04-09 03:13
@cjappl Can you help fix this for `fish`? I tried to do the same changes but it seems not work. :(

**Comment by airelil** [comment] 2020-04-09 03:51
Thanks! gss works too

**Comment by cjappl** [comment] 2020-04-09 04:25
@wfxr Yep no problem, I will check it out soon

**Comment by cjappl** [comment] 2020-04-09 16:25
Fish is fixed. Closing! thanks for reporting everyone :)

**Closed by cjappl** 2020-04-09 16:25 UTC
Labels: bug
