### ISSUE TITLE
gd with one file

### ISSUE THREAD

**Issue by omares** [wfxr/forgit#80] opened 2020-03-30 13:55 UTC
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

When running `gd` with one changed file, the diff editor does not open. Instead, you just see the "list" of changed files.

**Comment by cjappl** [comment] 2020-03-30 15:19
Hey @omares would you please make sure this works with bash too?

Thank you :)

**Comment by omares** [comment] 2020-03-31 09:12
@cjappl not sure if I get your message right. This is a bug that I experience when using forgit. I am able to reproduce it also on bash.

**Comment by cjappl** [comment] 2020-03-31 17:07
In the description, you just checked "zsh" instead of both "bash" and "zsh", just wanted to make sure the situation was reproducible in bash!

I'll check that box for you too

Thank you :)

**Comment by cjappl** [comment] 2020-04-08 21:46
@wfxr, just tagging you in case you didn't see this!

**Comment by wfxr** [comment] 2020-04-09 02:44
Hi @cjappl I noticed this but I didn't fully understand what @omares meant. `gd` works fine for me whether with one file or multiple files changed. Maybe some screntshots or gifs can help.
What about you @cjappl ? Can you repro the problem?

**Comment by cjappl** [comment] 2020-04-09 04:25
I'll give it a try tomorrow :)

**Comment by cjappl** [comment] 2020-04-09 16:27
I cannot repro this on either zsh or fish. Going to close for now. This could have been fixed with #74 ? 

@omares please pull the latest and try again. If you still see it, please provide detailed steps to repro and we can try again

**Comment by omares** [comment] 2020-04-20 22:09
Hey @cjappl and @wfxr, the issue still persists for me, albeit running the latest version. Enclosed is a gif recording of the issue. I created a fork of this repo and modified the `README.md`. 
In the recording you see me entering the `gd` command and as a result only receiving the list of changed files, instead of the diff interface.

![wxfr_forgit](https://user-images.githubusercontent.com/1375307/79804440-58eb3800-8364-11ea-9b68-e8c86dd2696c.gif)

**Comment by cjappl** [comment] 2020-04-20 22:50
Hmm, yeah I definitely see it in your gif, but unfortunately not on my side of things.

@wfxr any ideas on how to help track down the root cause? 

@omares would you report your versions of fzf, and zsh?

**Comment by wfxr** [comment] 2020-04-21 03:20
@omares Have you enabled `-1` or `--select-1` option globally for `fzf`?

**Comment by omares** [comment] 2020-04-22 13:28
@wfxr yes i do

```
export FZF_DEFAULT_OPTS='
    --ansi --border=horizontal --tabstop=4 --select-1 --exit-0
    --color fg:252,hl:67,fg+:252,bg+:235,hl+:81
    --color info:144,prompt:161,spinner:135,pointer:135,marker:118
``

**Comment by wfxr** [comment] 2020-04-23 02:27
@omares Since `--select-1` is enabled `fzf` will print and quit if only one line is accepted. So it is not recommanded to enable this option globally.

**Closed** 2020-05-07 11:35 UTC
